### ISSUE TITLE
module 'kpse' not found

### ISSUE THREAD

**Issue by xhain** [cereda/checkcites#10]
```
$ lua checkcites.lua
lua: checkcites.lua:620: module 'kpse' not found:
	no field package.preload['kpse']
	no file '/usr/local/share/lua/5.3/kpse.lua'
	no file '/usr/local/share/lua/5.3/kpse/init.lua'
	no file '/usr/local/lib/lua/5.3/kpse.lua'
	no file '/usr/local/lib/lua/5.3/kpse/init.lua'
	no file './kpse.lua'
	no file './kpse/init.lua'
	no file '/usr/local/lib/lua/5.3/kpse.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './kpse.so'
stack traceback:
	[C]: in function 'require'
	checkcites.lua:620: in local 'checkcites'
	checkcites.lua:867: in main chunk
	[C]: in ?
```

and

```
$ luarocks install kpse --check-lua-versions
kpse not found for Lua 5.3.
Checking if available for other Lua versions...
Checking for Lua 5.1...
Checking for Lua 5.2...
Checking for Lua 5.4...

Error: No results matching query were found for Lua 5.3.
kpse is not available for any Lua versions.
```

Running on OSX 10.15.5 with a fresh lua install

**Comment by cereda** [comment]
Hello!

Ah I see what's happening: `kpse` is a library from LuaTeX. In previous versions, `checkcites` used to be 100% compatible with the typical `lua` interpreter. However, recent features had to offer support for file lookup in the TeX tree, so the vanilla `lua` had to be dropped in favour of `texlua`.

Do you have MacTeX installed? If so, `checkcites` should be already in your path as a wrapper to proper script in the installed TeX tree. In order to run `checkcites.lua` in a standalone fashion, `texlua` is needed...

Hope that helps! :wink:

**Comment by xhain** [comment]
Thank you for your reply @cereda 

I have MacTeX installed. Do you know how I can run `checkcites` from the installed TeX tree? I generally use Overleaf, but clone it locally and can also compile the PDF locally using TeXstudio or command line.

**Comment by cereda** [comment]
Sure, I can help! Are you familiar with terminal usage? If so, open your terminal and test if `checkcites` is available. Simply type:

```bash
checkcites
```

and hit `ENTER`. You should get

```bash
     _           _       _ _
 ___| |_ ___ ___| |_ ___|_| |_ ___ ___
|  _|   | -_|  _| '_|  _| |  _| -_|_ -|
|___|_|_|___|___|_,_|___|_|_| |___|___|

checkcites.lua -- a reference checker script (v2.4)
Copyright (c) 2012, 2019, Enrico Gregorio, Paulo Roberto Massa Cereda

--------------------------------------------------------------------------
I am sorry, but you have not provided any command line argument, including
files to check and options. Make sure to invoke the script with the actual
arguments. Refer to the user documentation if you are unsure of how this
tool works. The script will end now.
```
as output. Then go the root folder where your TeX project is located and run

```bash
checkcites myproject
```

That should work. :wink: The default backend is `bibtex`, so if you rely on BibLaTeX, we need to add a few command line options. But that's a start. :wink: 

Cheerio!

**Comment by xhain** [comment]
Works like a charm! Thank you :)

**Comment by cereda** [comment]
Glad it worked! :wink:
