### ISSUE TITLE
Return value of ` $ checkcites` should return 1 if not everything is fine

### ISSUE THREAD

**Issue by Hotschke** [cereda/checkcites#3]
compare for example http://texdoc.net/texmf-dist/doc/support/match_parens/match_parens.pdf
where `echo $?` returns 1 if match_parens cannot match all parentheses.
Currently `echo $?` returns always 0, indicating no issues were found.

**Comment by cereda** [comment]
Hello! :smile: 

Agreed, it is a good plan, I will add the exit code to `checkcites`.

All the best!

**Comment by Hotschke** [comment]
Hello,

thanks for your tool. I am interested in adding automated testing to my latex manuscript git repositories. I try to facilitate git pre-commit hooks to avoid mistakes which can be spotted by the computer. I hope this will result in fewer mistakes in manuscripts leaving my desk. Other tools I am using are chktex, hunspell, languagetool, style-check.rb, match_parens, word_count and a few packages which report to the logfile such as onlyamsmath, nag, and refcheck.

Actually more of them do not report exit codes which will tell whether everything is fine or not.

So I am happy to see when you add it to checkcites.

Best wishes.

**Comment by cereda** [comment]
Oh my, I am terribly sorry for not updating the script for a long time!

I am ashamed of myself.

I am working on a new code and hopefully this new feature will be added. Thesis writing is taking a lot of my time and effort, but that's no excuse to not work on my projects.

Again, deeply sorry for the huge delay. 😞

**Comment by cereda** [comment]
Done, now I need to update the source code comments and the documentation itself. 😉
