### ISSUE TITLE
Whitespace between @article and {

### ISSUE THREAD

**Issue by daniel792** [cereda/checkcites#4]
The script seems to have a problem with references if there is whitespace in the corresponding definition in the .bib file, e.g. `@article {...}` as opposed to `@article{...}`.

It appears that the script does not find these references and hence treats them as undefined. I realize it is probably good practice to not use additional whitespace in this situation, but some standard sources for bibtex data (e.g. MathSciNet) do this automatically.

**Comment by cereda** [comment]
Hi, thanks for the great feedback!

You are right, the extra white spaces should be considered. One for my list of updates.

I am working on a complete rewrite of this script, and I will make sure to cover this issue. At the moment, however, I am finishing my thesis and I have to dedicate the majority of my time to it. Hopefully, I will be able to come up with a new code in the upcoming weeks. 😉 

Again, thank you very much for the feedback, it's highly appreciated!

**Comment by daniel792** [comment]
Thanks for your effort! Your thesis takes priority of course, but I'm looking forward to the new version. Cheers :)

**Comment by cereda** [comment]
Done, now I need to update the source code comments and the documentation itself. 😉
