### ISSUE TITLE
Add option to ignore crossrefs

### ISSUE THREAD

**Issue by blochberger** [cereda/checkcites#5]
I use a bibliography where some used entries `crossref` other entries. For example I have papers with the type `@inproceedings` and `crossref` the `@proceedings`. The `checkcites` script then reports all `@proceedings` as unused, even if papers are cited, that are part of these proceedings.

It would be nice to have a command line option, where you could exclude `crossref`'d entries from showing up if `crossref`ing entries are used.

**Comment by cereda** [comment]
Hello!

Oh I had no idea of this feature! I will take a closer look later on. Surely it is a nice addition to the script. Thanks for the feedback!

**Comment by FrankMittelbach** [comment]
@blochberger Normally BibTeX will insert a \cite command to the item it crossrefs, so if those are unresolved then in that case the solution is to rerun the document after BibTeX hs generated the bbl file. In other words there is something wrong in that case. However, I don#t doubt that there are BibTeX styles that don't, and in that case the option would be useful. What style are you using?

**Comment by blochberger** [comment]
I use `biblatex` with `biber` and usually `numeric` style.

**Comment by cereda** [comment]
Ouch, I am so sorry! For some reason, I forgot about this issue! I will mark as an upcoming feature for the next update.

**Comment by FrankMittelbach** [comment]
@cereda any updates on this?

**Comment by cereda** [comment]
@FrankMittelbach sorry, I got sidetracked by a couple of other tasks and an annoying flu that got me since last week. This feature does not seem too complicated, provided that the corresponding `.bib` file is well-formed (which I will always assume). I just need to take a closer look at the code and see how things could go without huge modifications. I will try to come back to this issue later on during the week (probably tomorrow).

**Comment by cereda** [comment]
@FrankMittelbach spot-on, in BibTeX, a cross-reference entry is inserted as a typical `\citation` in the `.aux` file. For example (taken from a [TeX.sx](https://tex.stackexchange.com/questions/148887) example):

```tex
\documentclass{article}

\begin{filecontents*}{bibliography.bib}
@proceedings{conf:2006,
  editor    = {Star, Patrick and Tentacles, Squidward},
  title     = {Proceedings of the 1st Conference on Marine Biology},
  booktitle = {Proceedings of the 1st Conference on Marine Biology},
  year      = 2006,
  month     = jan,
}

@inproceedings{proc:2006:02,
  editor    = {Star, Patrick and Tentacles, Squidward},
  booktitle = {Proceedings of the 1st Conference on Marine Biology},
  year      = 2006,
  month     = jan,
  title     = {How To Live Underwater},
  author    = {Squarepants, SpongeBob},
  pages     = {1--8},
}

@inproceedings{proc:2006:01,
  title     = {How To Live Underwater},
  author    = {Squarepants, SpongeBob},
  pages     = {1--8},
  crossref  = {conf:2006}
}
\end{filecontents*}

\begin{document}
\cite{proc:2006:01}
\bibliographystyle{plain}
\bibliography{bibliography}
\end{document}
```

The corresponding `.aux` file is

```
\relax 
\citation{proc:2006:01}
\bibstyle{plain}
\bibdata{bibliography}
\bibcite{proc:2006:01}{1}
\citation{conf:2006}
\bibcite{conf:2006}{2}
```

So, in this particular scenario, `checkcites` will report only one unused reference, which is

```
Unused references in your TeX document: 1
=> proc:2006:02
```

Enrico and I will take a closer look on how BibLaTeX implements this. Mostly likely their key is different than a typical citation, as it's done with BibTeX (and thus there's no semantic difference from an actual reference and a cross-reference). Will report soon. :wink:

**Comment by cereda** [comment]
Actually, forget what I just said, I had some old files in my machine. :wink: I tried to implement something, let's see if it works...

**Comment by cereda** [comment]
@FrankMittelbach the current code ignores cross-references as default. I was wondering if I should turn it off and enable this check through a command line flag (e.g, `--ignore-crossrefs`). Thoughts?
